# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load": "00_eda.ipynb",
         "findCategoricalCandidates": "00_eda.ipynb",
         "categoricalTally": "00_eda.ipynb"}

modules = ["eda.py"]

doc_url = "https://mikhas.github.io/sully/"

git_url = "https://github.com/mikhas/sully/tree/master/"

def custom_doc_links(name): return None
