# AUTOGENERATED! DO NOT EDIT! File to edit: 01_analysis.ipynb (unless otherwise specified).

__all__ = ['makeCatCodes']

# Cell
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sully import eda

# Cell
def makeCatCodes(data:pd.DataFrame, columns:list)->pd.DataFrame:
    for col in columns:
        data[col] = pd.Categorical(data[col])

    codes = {}
    for col in columns:
        codes[col] = data[col].cat.codes

    return pd.DataFrame(codes)