# AUTOGENERATED! DO NOT EDIT! File to edit: 00_eda.ipynb (unless otherwise specified).

__all__ = ['columnSizeNotNa', 'findCategoricalCandidates']

# Cell
from zipfile import ZipFile
import pandas as pd
import numpy as np
import seaborn as sns

# Cell
def columnSizeNotNa(data:pd.DataFrame)->pd.DataFrame:
    return pd.DataFrame(
        [(col, (len(data[data[col].notna() == True]))) for col in data.columns],
        columns=['name', 'size']
    ).sort_values(by='size')

# Cell

def findCategoricalCandidates(data:pd.DataFrame, ratio:float=0.01)->pd.DataFrame:
    result = pd.DataFrame(
        [(col, len(data[col].unique())) for col in data.columns],
        columns=['name', 'size']
    ).sort_values(by='size')

    n = len(data)
    return result[result['size'] / n < ratio]